# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import edc_visit_schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edc_content_type_map', '0002_auto_20160625_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipForm',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('category', models.CharField(default='subject', help_text='In lowercase, this should be a valid subject type (as in registered_subject).', max_length=35, null=True, unique=True)),
                ('visible', models.BooleanField(default=True, help_text='If not visible on the dashboard, you have to write code to populate it yourself.')),
                ('app_label', models.CharField(max_length=25, null=True)),
                ('model_name', models.CharField(max_length=25, null=True)),
                ('content_type_map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edc_content_type_map.ContentTypeMap')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=25, unique=True)),
                ('grouping_key', models.CharField(blank=True, help_text='may specify a common value to group a number of membership forms so that when one of the group is keyed, the others are no longer shown.', max_length=25, null=True)),
                ('comment', models.CharField(blank=True, max_length=25, null=True)),
                ('membership_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_visit_schedule.MembershipForm')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='VisitDefinition',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('time_point', models.IntegerField(default=0, verbose_name='Time point')),
                ('base_interval', models.IntegerField(default=0, help_text='Interval from base timepoint 0 as an integer.', verbose_name='Base interval')),
                ('base_interval_unit', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], default='D', max_length=10, verbose_name='Base interval unit')),
                ('lower_window', models.IntegerField(default=0, verbose_name='Window lower bound')),
                ('lower_window_unit', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], default='D', max_length=10, verbose_name='Lower bound units')),
                ('upper_window', models.IntegerField(default=0, verbose_name='Window upper bound')),
                ('upper_window_unit', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], default='D', max_length=10, verbose_name='Upper bound units')),
                ('grouping', models.CharField(blank=True, max_length=25, null=True, verbose_name='Grouping')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, validators=[django.core.validators.MaxLengthValidator(6)])),
                ('title', models.CharField(db_index=True, max_length=35, verbose_name='Title')),
                ('instruction', models.TextField(blank=True, max_length=255, verbose_name='Instructions')),
                ('schedule', models.ManyToManyField(blank=True, help_text='Visit definition may be used in more than one schedule', to='edc_visit_schedule.Schedule')),
                ('visit_tracking_content_type_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='edc_content_type_map.ContentTypeMap', validators=[edc_visit_schedule.models.is_visit_tracking_model], verbose_name='Visit Tracking Model')),
            ],
            options={
                'ordering': ['code', 'time_point'],
            },
        ),
    ]
